version: '3.1'

services:
  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
      - ./logs:/var/log/nginx
    #ports:
    #  - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  node:
    image: node:16.14
    network_mode: host
    user: node
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
      - ./logs:/home/node/logs
    #ports:
    #  - '3000:3000'
    command: 'node app/server.js'